{
 "title": "Axelar Network dashboard",
 "description": "Empowering dApp builders and blockchain ecosystems - Unlocking cross-chain communication",
 "tags": [
  "Blockchain",
  "Cosmos",
  "axelar"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(tendermint_consensus_height, chain_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$chain_id network overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<table width=\"100%\" style=\"margin: 0px; border: 0px transparent; border-color: transparent\">\r\n<thead>\r\n  <tr>\r\n    <td style=\"text-align:left\">\r\n      <a href=\"https://axelar.network/\" target=\"_blank\">\r\n      <img width=\"250px\" src=\"https://s3.amazonaws.com/assets.knackhq.com/assets/60e363e6ad9a36001e917822/logos/untitleddesign2111.png\" />\r\n      </a>\r\n</td>\r\n    <td style=\"text-align:right\">\r\n      <a href=\"https://www.pops.one\" target=\"_blank\">\r\n      <img src=\"https://pops.one/img/logo.png\" /></td>\r\n      </a>\r\n  </tr>\r\n</thead>\r\n</table>\r\n"
   }
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total tendermint Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 / (delta(tendermint_consensus_block_interval_seconds_count[30m])/30)"
    }
   ]
  },
  {
   "title": "Total Bonded Tokens",
   "type": "stat",
   "description": "Total power of all validators",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "AXL Tx count / failed",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "axelar_tx_count", "legendFormat": "total tx count" },
    { "expr": "axelar_tx_failed", "legendFormat": "tx failed" }
   ]
  },
  {
   "title": "axelar_bitcoin_total_deposit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "axelar_bitcoin_total_deposit" }
   ]
  },
  {
   "title": "btc master key rotation",
   "type": "stat",
   "description": "axelar bitcoin master key rotation count",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axelar_tss_bitcoin_master_key_rotation_count"
    }
   ]
  },
  {
   "title": "eth master key rotation",
   "type": "stat",
   "description": "axelar eth master key rotation count",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axelar_tss_ethereum_master_key_rotation_count"
    }
   ]
  },
  {
   "title": "btc sec key rotation",
   "type": "stat",
   "description": "axelar bitcoin secondary key rotation count",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axelar_tss_bitcoin_secondary_key_rotation_count"
    }
   ]
  },
  {
   "title": "eth secondary key rotation",
   "type": "stat",
   "description": "axelar eth secondary key rotation count",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axelar_tss_ethereum_secondary_key_rotation_count"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Tendermint instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "instance"
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Is fast syncing ?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_fast_syncing"
    }
   ]
  },
  {
   "title": "Is state syncing ?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_state_syncing"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peer_send_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Hidden row used for alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "5m Network block difference",
     "type": "timeseries",
     "description": "shouldn't be 0 network is stuck",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "delta(tendermint_consensus_height[5m])"
      }
     ]
    },
    {
     "title": "Validator 5m block difference",
     "type": "timeseries",
     "description": "shouldn't be 0 unless validator node is stuck",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "delta(tendermint_consensus_latest_block_height[5m])"
      }
     ]
    }
   ]
  }
 ]
}