{
 "title": "Erigon Prometheus - experimental",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantile", "query": "0.5, 0.9, 0.97, 0.99, 1" },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Blocks execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync Stages progress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\"}",
     "legendFormat": "{{ stage }}: {{instance}}"
    }
   ]
  },
  {
   "title": "Sync Stages progress rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(sync{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "{{ stage }}:  {{instance}}"
    }
   ]
  },
  {
   "title": "Block Execution speed ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "execution: {{instance}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(db_commit_seconds_count{phase=\"total\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "commit: {{instance}}"
    }
   ]
  },
  {
   "title": "Commit speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_commit_seconds{phase=\"total\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_total: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_gc: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"write\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_write: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"sync\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_sync: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    }
   ]
  },
  {
   "title": "GC and State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "db_gc_leaf{instance=~\"$instance\"}",
     "legendFormat": "gc_leaf: {{instance}}"
    },
    {
     "expr": "db_gc_overflow{instance=~\"$instance\"}",
     "legendFormat": "gc_overflow: {{instance}}"
    },
    {
     "expr": "db_state_leaf{instance=~\"$instance\"}",
     "legendFormat": "state_leaf: {{instance}}"
    },
    {
     "expr": "db_state_branch{instance=~\"$instance\"}",
     "legendFormat": "state_branch: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Pages Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(db_pgops_clone{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "clone: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_split{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "split: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_spill{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "spill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_wops{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "wops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_unspill{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "unspill: {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tx_limit{instance=~\"$instance\"}",
     "legendFormat": "limit: {{instance}}"
    },
    {
     "expr": "tx_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Rusage Total (\"last value\" - \"first value\" on selected period)",
   "type": "stat",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "ru_inblock{instance=~\"$instance\"}",
     "legendFormat": "inblock: {{instance}}"
    },
    {
     "expr": "ru_outblock{instance=~\"$instance\"}",
     "legendFormat": "outblock: {{instance}}"
    },
    {
     "expr": "ru_minflt{instance=~\"$instance\"}",
     "legendFormat": "minflt: {{instance}}"
    },
    {
     "expr": "ru_majflt{instance=~\"$instance\"}",
     "legendFormat": "majflt: {{instance}}"
    },
    {
     "expr": "system_disk_readbytes{instance=~\"$instance\"}",
     "legendFormat": "system_disk_readbytes: {{instance}}"
    },
    {
     "expr": "system_disk_writebytes{instance=~\"$instance\"}",
     "legendFormat": "system_disk_writebytes: {{instance}}"
    },
    {
     "expr": "db_pgops_newly{instance=~\"$instance\"}",
     "legendFormat": "pgops_newly: {{instance}}"
    },
    {
     "expr": "db_pgops_cow{instance=~\"$instance\"}",
     "legendFormat": "pgops_cow: {{instance}}"
    },
    {
     "expr": "db_pgops_clone{instance=~\"$instance\"}",
     "legendFormat": "pgops_clone: {{instance}}"
    },
    {
     "expr": "db_pgops_split{instance=~\"$instance\"}",
     "legendFormat": "pgops_split: {{instance}}"
    },
    {
     "expr": "db_pgops_merge{instance=~\"$instance\"}",
     "legendFormat": "pgops_merge: {{instance}}"
    },
    {
     "expr": "db_pgops_spill{instance=~\"$instance\"}",
     "legendFormat": "pgops_spill: {{instance}}"
    },
    {
     "expr": "db_pgops_unspill{instance=~\"$instance\"}",
     "legendFormat": "pgops_unspill: {{instance}}"
    },
    {
     "expr": "db_pgops_wops{instance=~\"$instance\"}",
     "legendFormat": "pgops_wops: {{instance}}"
    }
   ]
  },
  {
   "title": "Read/Write syscall/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_io_write_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "in: {{instance}}"
    },
    {
     "expr": "rate(process_io_read_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "out: {{instance}}"
    }
   ]
  },
  {
   "title": "getrusage: minflt - soft page faults (reclaims), majflt - hard faults",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(process_minor_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "soft: {{instance}}"
    },
    {
     "expr": "rate(process_major_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "hard: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "go_cgo_calls_count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_cgo_calls_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "go_cgo_calls_count: {{instance}}"
    }
   ]
  },
  {
   "title": "go memstat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_stack_sys_bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_sys_bytes"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go/goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go/threads: {{instance}}"
    }
   ]
  },
  {
   "title": "mem: resident set size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident mem: {{instance}}"
    },
    {
     "expr": "mem_data{instance=~\"$instance\"}",
     "legendFormat": "data: {{instance}}"
    },
    {
     "expr": "mem_stack{instance=~\"$instance\"}",
     "legendFormat": "stack: {{instance}}"
    },
    {
     "expr": "mem_locked{instance=~\"$instance\"}",
     "legendFormat": "locked: {{instance}}"
    },
    {
     "expr": "mem_swap{instance=~\"$instance\"}",
     "legendFormat": "swap: {{instance}}"
    }
   ]
  },
  {
   "title": "GC Stop the World per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{quantile=\"0.75\",instance=~\"$instance\"}[$rate_interval])"
    }
   ]
  },
  {
   "title": "Process Mem: allocate objects/sec, free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "go_memstats_mallocs_total"
    },
    {
     "expr": "rate(go_memstats_frees_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "go_memstats_frees_total"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_system_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "increase(process_cpu_seconds_user_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "iowait: {{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Host VMem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmem_total{instance=~\"$instance\"}",
     "legendFormat": "total: {{instance}}"
    },
    {
     "expr": "vmem_available{instance=~\"$instance\"}",
     "legendFormat": "available: {{instance}}"
    },
    {
     "expr": "vmem_used{instance=~\"$instance\"}",
     "legendFormat": "used: {{instance}}"
    },
    {
     "expr": "vmem_buffers{instance=~\"$instance\"}",
     "legendFormat": "buffers: {{instance}}"
    },
    {
     "expr": "vmem_cached{instance=~\"$instance\"}",
     "legendFormat": "cached: {{instance}}"
    },
    {
     "expr": "vmem_writeback{instance=~\"$instance\"}",
     "legendFormat": "writeback: {{instance}}"
    },
    {
     "expr": "vmem_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    },
    {
     "expr": "vmem_shared{instance=~\"$instance\"}",
     "legendFormat": "shared: {{instance}}"
    },
    {
     "expr": "vmem_mapped{instance=~\"$instance\"}",
     "legendFormat": "mapped: {{instance}}"
    }
   ]
  },
  { "title": "TxPool v2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pool_process_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "pool_process_remote_txs: {{ instance }}"
    },
    {
     "expr": "pool_add_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "pool_add_remote_txs: {{ instance }}"
    },
    {
     "expr": "pool_new_block{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "pool_new_block: {{ instance }}"
    },
    {
     "expr": "pool_write_to_db{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "pool_write_to_db: {{ instance }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(pool_process_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_process_remote_txs_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_add_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_add_remote_txs_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_new_block_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_new_block_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_write_to_db_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_write_to_db_count: {{ instance }}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(delta(pool_cache_total{result=\"hit\",instance=~\"$instance\"}[1m]))/sum(delta(pool_cache_total{instance=~\"$instance\"}[1m])) ",
     "legendFormat": "hit rate: {{ instance }} "
    }
   ]
  },
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pool_write_to_db_bytes{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_write_to_db_bytes: {{ instance }}"
    }
   ]
  },
  {
   "title": "Senders",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 67 },
   "targets": [
    {
     "expr": "rate(pool_senders_evicted{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_senders_evicted: {{ instance }}"
    }
   ]
  },
  {
   "title": "Hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Merkle Root calculation (stage 5)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "trie_subtrieloader_flatdb{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "trie_subtrieloader_flatdb: {{quantile}}, {{instance}}"
      },
      {
       "expr": "trie_subtrieloader_witnessdb{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "trie_subtrieloader_witnessdb: {{quantile}}, {{instance}}"
      }
     ]
    },
    {
     "title": "AutoDupsort Call/Sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_op_set_count{instance=~\"$instance\"}[1m])"
      },
      {
       "expr": "rate(db_op_set_range_count{instance=~\"$instance\"}[1m])"
      },
      {
       "expr": "rate(db_op_get_count{instance=~\"$instance\"}[1m])"
      },
      {
       "expr": "rate(db_op_get_both{instance=~\"$instance\"}[1m])"
      },
      {
       "expr": "rate(db_op_get_both_range_count{instance=~\"$instance\"}[1m])"
      },
      {
       "expr": "db_op_put{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_put_current{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "db.Get() latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "db_get{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "get: {{quantile}}, {{instance}}"
      }
     ]
    },
    {
     "title": "AutoDupsort Call/Sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "db_op_set{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_set_range{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_get{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_get_both{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_get_both_range{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_put{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_put_current{quantile=\"$quantile\",instance=~\"$instance\"}"
      },
      {
       "expr": "db_op_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "AutoDupsort Put latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "mdbx_put_direct{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_direct: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_direct{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_direct: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_both_range{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_both_range: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_both_range{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_both_range: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_seek_exact{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_seek_exact: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_seek_exact{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_seek_exact: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_no_overwrite: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_no_overwrite: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_upsert{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_upsert: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_upsert{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_upsert: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_current2{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_current2: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_current2{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_current2: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_upsert2{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_upsert2: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_put_upsert2{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_upsert2: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_del_current{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_put_current: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_del_current{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_del_current: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_seek_exact2{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_seek_exact2: {{quantile}}, {{instance}}"
      },
      {
       "expr": "mdbx_seek_exact2{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "mdbx_seek_exact2: {{quantile}}, {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stage_headers{instance=~\"$instance\"}",
     "legendFormat": "Header: {{instance}}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stage_headers{instance=~\"$instance\"}",
     "legendFormat": "blocks:{{instance}}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "receipt: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "local: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\"}[1m])",
     "legendFormat": "valid: {{instance}}"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid: {{instance}}"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  {
   "title": "Private api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC call, error rates ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_started_total{instance=~\"$instance\"}[1m]))",
       "legendFormat": "Calls: {{grpc_service}}.{{grpc_method}}, {{instance}}"
      },
      {
       "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_handled_total{instance=~\"$instance\",grpc_code!=\"OK\"}[1m])) ",
       "legendFormat": "Errors: {{grpc_service}}.{{grpc_method}}, {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}